### DISCUSSION TITLE
How to change the base url for nexus?

### DISCUSSION THREAD

**Discussion by chance2021** [BlueBrain/nexus#2736] [Q&A] [answered]
Hi, 

I would like to change the base url for nexus from root `/ ` to `/nexus` in the deployment. Just wondering how to achieve it? Any guide will be much appreciated!

**Comment by umbreak** [comment, marked as answer]
You can change the base url for nexus using the configuration field `app.http.base-uri`

**Reply by bogdanromanx** [reply]
This is the relevant section of the configuration: https://github.com/BlueBrain/nexus/blob/v1.5.0/delta/app/src/main/resources/app.conf#L15

So you can just start delta adding the `-Dapp.http.base-uri=http://localhost:8080/nexus/v1` to achieve the result you're looking for.

**Reply by chance2021** [reply]
Thanks for the reply@umbreak  @bogdanromanx !! I have added the suggested setting (`-Dapp.http.base-uri=http://localhost:8080/nexus/v1`) in [delta.yaml](https://bluebrainnexus.io/docs/getting-started/running-nexus/minikube/delta.yaml) file (as I am using k8s as deployment) and  I also changed the ingress path (`path: /nexus/v1`) in the same file. However, when I was trying to create a realm after the change deployed, it throws me below error... I was able to create a realm without any issue before this update. Any idea what maybe the issue? Also, should I update `BASE_PATH` in [web.yaml](https://bluebrainnexus.io/docs/getting-started/running-nexus/minikube/web.yaml) for nexus-web as well? Thanks

```
$ curl -XPUT   -H "Content-Type: application/json"   "http://<K8s Ingress Nginx IP>/nexus/v1/realms/vre"   -d '{
        "name":"vre",
        "openIdConfig":"http://<KEYCLOAK IP>/auth/realms/vre/.well-known/openid-configuration",
        "logo":"http://localhost:8080/logo.png"
      }'


{"@context":"https://bluebrain.github.io/nexus/contexts/error.json","@type":"ResourceNotFound","reason":"The requested resource does not exist."}
```

**Reply by bogdanromanx** [reply]
Huh? Are you trying to deploy to Minikube or Kubernetes?
If it's minikube, the value of the flag should be `-Dapp.http.base-uri="$PUBLIC_URI/nexus/v1"` (also notice the surrounding quotes).

Also make sure the value change did not alter the indenting of the yaml file (all the startup parameters need to have the same level of indentation).

**Reply by bogdanromanx** [reply]
> Also, should I update BASE_PATH in web.yaml for nexus-web as well?

That should be updated as well, yes.

**Reply by chance2021** [reply]
@bogdanromanx   Thanks for the quick response! I did change to `-Dapp.http.base-uri="$PUBLIC_URI/v1"` in in [delta.yaml ](https://bluebrainnexus.io/docs/getting-started/running-nexus/minikube/delta.yaml) file, but I got the same error.. Actually,  I am trying to deploy to Kubernetes. I don't see any instruction for Kubernetes but Minikube in [the official document.](https://bluebrainnexus.io/docs/getting-started/running-nexus/index.html). So I just used the Minikube yaml. Will this be matter? Or if there is any place I can find the yaml files for Kubernetes?

**Reply by bogdanromanx** [reply]
Is it `-Dapp.http.base-uri="$PUBLIC_URI/v1"` or `-Dapp.http.base-uri="$PUBLIC_URI/nexus/v1"`?

Can you hardcode the value to your actual "public" domain, e.g. `-Dapp.http.base-uri="https://my.website/nexus/v1"`, does that work?

**Reply by chance2021** [reply]
Hi @bogdanromanx , sorry, it was a typo... I should be `-Dapp.http.base-uri="$PUBLIC_URI/nexus/v1"`. 

I just tried to replace the value with my certified domain name in [delta.yaml](https://bluebrainnexus.io/docs/getting-started/running-nexus/minikube/delta.yaml), unfortunately there is no luck and still getting the same error as above... 

```
curl "https://<public domain name>/nexus/v1/realms"

{"@context":"https://bluebrain.github.io/nexus/contexts/error.json","@type":"ResourceNotFound","reason":"The requested resource does not exist."}
```

I also tried `curl "https://<public domain name>/v1/realms" ` without `/nexus` and it returns below 404 error, which means the change I have made (including ingress) has been taken effect, but for some reason the api endpoint cannot be found in that URI... Let me know if you would like to have more information. Thanks!
```
curl "https://<public domain name>/v1/realms"

default backend - 404
```

**Reply by bogdanromanx** [reply]
I think I figured it out... you're hitting a bug in the 1.5.0 release, please bump the version in the delta yaml to 1.5.1. You can see the list of changes across versions in the documentation: https://bluebrainnexus.io/docs/releases/index.html or in the github releases: https://github.com/BlueBrain/nexus/releases

**Reply by chance2021** [reply]
Hi @bogdanromanx , after changing the version to **1.5.1** in **delta.yaml**, I can see the proper response with the realm info under the relative path! Thanks so much!!
```
curl "https://<public domain name>/nexus/v1/realms"
```

I also changed the version in **web.yaml** and seems like it also fixed missing coin issue!

However, when I was trying to login with a integrated keycloak account, **the callback url is pointing me to an error** with `default backend - 404`. What I have noticed is there is an `\` missing after the relative path `\nexus`. For example, the callback url is like this

http://\<ip address>\/nexus#state=<state from Keycloak>&session_state=<session state from Keycloak>&access_token=<access token from Keycloak>&token_type=bearer&expires_in=900


If I add a `/` after `/nexus` before `#state`, the url will work. 

http://\<ip address> /nexus/#state=<state from Keycloak>&session_state=<session state from Keycloak>&access_token=<access token from Keycloak>&token_type=bearer&expires_in=900
 ----------------------------------^---------------------------------------------------------------------------------------------------------


Just wondering if you have any idea **how I can change this callback url**? I have been played around in Keycloak/nexus-web client all day by changing the URL in the fields "Root URL"/"Base URL"/"Admin URL" but still cannot figure out how to update the callback url. Not sure if it is something we have to do via nexus delta api, just like what I have setup the realm in the first place...

**Note**: The below is the **setting in my Keycloak**...
```
Client ID:   nexus-web
Name:   nexus-web
Client Protocal:   openid-connect
Access Type:   public
Standard Flow Enabled:   ON
Implicit Flow Enabled:   ON
Direct Access Grants Enabled:  ON
Root URL:     http://<ip address>/nexus/
Valid Redirect URIs:     *
Base URL:   http://<ip address>/nexus/
Admin URL:     http://<ip address>/nexus/
Web Origins:   <blank>
```

**Reply by bogdanromanx** [reply]
This seems like an issue with the ingress configuration because a "default backend - 404" means that a target service could not be picked up by the ingress. You should check the ingress configuration for the web.yaml and its BASE_PATH configuration as well.

**Reply by chance2021** [reply]
Thanks for the reply @bogdanromanx !  Actually, this issue only happens after successfully logging in the Keycloak and it is returning back to the web. I can access the web with `http://<ip address>/nexus/`  without any issue. Here are the configuration for the nexus-web and delta that have changed...

**web.yaml**
```
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-web
  namespace: nexus
  labels:
    app: nexus-web
    group: service
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: nexus-web
    group: service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus-web
  namespace: nexus
  labels:
    app: nexus-web
    group: service
spec:
  replicas: 1
  serviceName: nexus-web
  selector:
    matchLabels:
      app: nexus-web
  template:
    metadata:
      labels:
        app: nexus-web
        group: service
    spec:
      containers:
        - name: nexus-web
          image: 'bluebrain/nexus-web:1.5.1'
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: PUBLIC_IP
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: public.ip
            - name: BASE_PATH
              value: /nexus/
            - name: HOST_NAME
              value: 'http://$(PUBLIC_IP)'
            - name: API_ENDPOINT
              value: 'http://$(PUBLIC_IP)/nexus/v1'
            - name: PLUGINS_MANIFEST_PATH
              value: 'http://$(PUBLIC_IP)/plugins'
            - name: PLUGINS_CONFIG_PATH
              value: /opt/nexus/public/plugins/plugins.config.json
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: nexus-web
  namespace: nexus
spec:
  rules:
  - http:
      paths:
      - backend:
            serviceName: nexus-web
            servicePort: 8000
        path: /nexus/
        pathType: Prefix
---
```

**delta.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: delta
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: delta
    group: service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: delta-hd
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  ports:
  - name: remoting
    port: 25520
    protocol: TCP
    targetPort: 25520
  - name: prometheus
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    app: delta
    group: service
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-delta
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: delta
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  replicas: 1
  serviceName: delta-hd
  selector:
    matchLabels:
      app: delta
  template:
    metadata:
      namespace: nexus
      labels:
        app: delta
        group: service
    spec:
      containers:
      - name: delta
        image: bluebrain/nexus-delta:1.5.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: storage
          mountPath: /opt/binaries
        env:
        - name: PUBLIC_IP
          valueFrom:
            configMapKeyRef:
              name: config
              key: public.ip
        - name: BIND_INTERFACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REMOTING_INTERFACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PUBLIC_URI
          value: 'http://$(PUBLIC_IP)'
        - name: JAVA_OPTS
          value: '-Xms256m -Xmx1g'
        - name: DELTA_PLUGINS
          value: '/opt/docker/plugins'
        - name: REPAIR_FROM_MESSAGES
          value: 'false'
        command:
        - '/bin/bash'
        - '-c'
        - >
           /opt/docker/bin/delta-app
           -Dapp.instance.interface="$BIND_INTERFACE"
           -Dapp.http.interface="$BIND_INTERFACE"
           -Dapp.http.base-uri="$PUBLIC_URI/nexus/v1"
           -Dapp.cluster.remote-interface="$BIND_INTERFACE.delta-hd.nexus.svc.cluster.local"
           -Dapp.cluster.seeds="delta-0.delta-hd.nexus.svc.cluster.local:25520"
           -Dapp.database.cassandra.tables-autocreate="true"
           -Dapp.database.cassandra.keyspace-autocreate="true"
           -Dapp.database.cassandra.journal.keyspace-autocreate="true"
           -Dapp.database.cassandra.journal.tables-autocreate="true"
           -Dapp.database.cassandra.snapshot.keyspace-autocreate="true"
           -Dapp.database.cassandra.snapshot.tables-autocreate="true"
           -Dakka.http.server.parsing.max-content-length="2MiB"
           -Dakka.http.client.parsing.max-content-length="100g"
           -Dakka.http.server.request-timeout="5 minutes"
           -Dakka.remote.artery.advanced.maximum-frame-size="3MiB"
           -Dapp.database.cassandra.contact-points.0="cassandra-0.cassandra.nexus.svc.cluster.local:9042"
           -Dplugins.elasticsearch.base="http://elasticsearch.nexus.svc.cluster.local:9200"
           -Dplugins.blazegraph.base="http://blazegraph.nexus.svc.cluster.local/blazegraph"
           -Dplugins.storage.storages.disk.default-volume="/opt/binaries"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 25520
          name: remoting
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 6Gi
          limits:
            cpu: 4000m
            memory: 6Gi
        livenessProbe:
          tcpSocket:
            port: http
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: remoting
          failureThreshold: 30
          successThreshold: 1
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage-delta
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: delta
  namespace: nexus
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: delta
              servicePort: 80
            path: /nexus/v1
            pathType: Prefix
---
```

**Reply by chance2021** [reply]
Hi @bogdanromanx , actually I have figured the issue. You are right and **it was the ingress issue**. After changing the path in ingress for both **web.yaml** and **delta.yaml** by **adding** `(/|$)` in the end of url (i.g. **/nexus(/|$)** and **/nexus/v1(/|$)**) , plus the change mentioned above, now I can access the site with relative url and then correctly pointed back after logging to SSO provider without any issue!!  

Thanks so much for your instruction and patient!! REALLY appreciated it!!!

---
**Note**: Here is the change I have made in respective files.
**web.yaml**
```
kind: StatefulSet
spec:
 template:          
    spec:
      containers:
        - name: nexus-web
          image: 'bluebrain/nexus-web:1.5.1'
          env:
            - name: BASE_PATH
              value: /nexus/
            - name: API_ENDPOINT
              value: 'http://$(PUBLIC_IP)/nexus/v1'          
            - name: PLUGINS_MANIFEST_PATH
              value: 'https://vre-staging.indocresearch.org/nexus/plugins'

kind: Ingress
spec:
  rules:
  - http:
      paths:
      - backend:
            serviceName: nexus-web
            servicePort: 8000
        path: /nexus(/|$)
```        
        
        

**delta.yaml**
```
kind: StatefulSet    
    group: service
spec:
  template:
    spec:
      containers:
      - name: delta
        image: bluebrain/nexus-delta:1.5.1   
        command:
        - '/bin/bash'
        - '-c'
        - >
           -Dapp.http.base-uri="$PUBLIC_URI/nexus/v1" 
           
kind: Ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: delta
              servicePort: 80
            path: /nexus/v1(/|$)
```
---

**Note**: Here are the full version of configuration files I have used for the relative url changed which is working in my environment, just in case if someone needs it...

**web.yaml**
```
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-web
  namespace: nexus
  labels:
    app: nexus-web
    group: service
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: nexus-web
    group: service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus-web
  namespace: nexus
  labels:
    app: nexus-web
    group: service
spec:
  replicas: 1
  serviceName: nexus-web
  selector:
    matchLabels:
      app: nexus-web
  template:
    metadata:
      labels:
        app: nexus-web
        group: service
    spec:
      containers:
        - name: nexus-web
          image: 'bluebrain/nexus-web:1.5.1'
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: PUBLIC_IP
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: public.ip
            - name: BASE_PATH
              value: /nexus/
            - name: HOST_NAME
              value: 'http://$(PUBLIC_IP)/'
            - name: API_ENDPOINT
              value: 'http://$(PUBLIC_IP)/nexus/v1'
            - name: PLUGINS_MANIFEST_PATH
              value: 'http://$(PUBLIC_IP)/nexus/plugins'
            - name: PLUGINS_CONFIG_PATH
              value: /opt/nexus/public/plugins/plugins.config.json
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: nexus-web
  namespace: nexus
spec:
  rules:
  - http:
      paths:
      - backend:
            serviceName: nexus-web
            servicePort: 8000
        path: /nexus(/|$)
        pathType: Prefix
---
```

**delta.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: delta
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: delta
    group: service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: delta-hd
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  ports:
  - name: remoting
    port: 25520
    protocol: TCP
    targetPort: 25520
  - name: prometheus
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    app: delta
    group: service
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-delta
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: delta
  namespace: nexus
  labels:
    app: delta
    group: service
spec:
  replicas: 1
  serviceName: delta-hd
  selector:
    matchLabels:
      app: delta
  template:
    metadata:
      namespace: nexus
      labels:
        app: delta
        group: service
    spec:
      containers:
      - name: delta
        image: bluebrain/nexus-delta:1.5.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: storage
          mountPath: /opt/binaries
        env:
        - name: PUBLIC_IP
          valueFrom:
            configMapKeyRef:
              name: config
              key: public.ip
        - name: BIND_INTERFACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REMOTING_INTERFACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PUBLIC_URI
          value: 'http://$(PUBLIC_IP)'
        - name: JAVA_OPTS
          value: '-Xms256m -Xmx1g'
        - name: DELTA_PLUGINS
          value: '/opt/docker/plugins'
        - name: REPAIR_FROM_MESSAGES
          value: 'false'
        command:
        - '/bin/bash'
        - '-c'
        - >
           /opt/docker/bin/delta-app
           -Dapp.instance.interface="$BIND_INTERFACE"
           -Dapp.http.interface="$BIND_INTERFACE"
           -Dapp.http.base-uri="$PUBLIC_URI/nexus/v1"
           -Dapp.cluster.remote-interface="$BIND_INTERFACE.delta-hd.nexus.svc.cluster.local"
           -Dapp.cluster.seeds="delta-0.delta-hd.nexus.svc.cluster.local:25520"
           -Dapp.database.cassandra.tables-autocreate="true"
           -Dapp.database.cassandra.keyspace-autocreate="true"
           -Dapp.database.cassandra.journal.keyspace-autocreate="true"
           -Dapp.database.cassandra.journal.tables-autocreate="true"
           -Dapp.database.cassandra.snapshot.keyspace-autocreate="true"
           -Dapp.database.cassandra.snapshot.tables-autocreate="true"
           -Dakka.http.server.parsing.max-content-length="2MiB"
           -Dakka.http.client.parsing.max-content-length="100g"
           -Dakka.http.server.request-timeout="5 minutes"
           -Dakka.remote.artery.advanced.maximum-frame-size="3MiB"
           -Dapp.database.cassandra.contact-points.0="cassandra-0.cassandra.nexus.svc.cluster.local:9042"
           -Dplugins.elasticsearch.base="http://elasticsearch.nexus.svc.cluster.local:9200"
           -Dplugins.blazegraph.base="http://blazegraph.nexus.svc.cluster.local/blazegraph"
           -Dplugins.storage.storages.disk.default-volume="/opt/binaries"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 25520
          name: remoting
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 6Gi
          limits:
            cpu: 4000m
            memory: 6Gi
        livenessProbe:
          tcpSocket:
            port: http
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: remoting
          failureThreshold: 30
          successThreshold: 1
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage-delta
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: delta
  namespace: nexus
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: delta
              servicePort: 80
            path: /nexus/v1(/|$)
            pathType: Prefix
---

```

```
