### ISSUE TITLE
Investigate resource values for express in openshift

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#234]
child of #225

At the moment we have:

```yaml
resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
```
